# Use the official OpenJDK 11 image as the base image
FROM adoptopenjdk:17-jdk-hotspot

# Add Maintainer Info
LABEL maintainer="example@example.com"

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=target/facebooklogin-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
COPY ${JAR_FILE} app.jar

# Run the jar file 
ENTRYPOINT ["java","-jar","/app.jar"]