replicaCount: 1

image:
  repository: facebooklogin
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}